---
abstract: 'simple command line option parser'
author:
  - 'Kan Fushihara <kan.fushihara at gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: opts
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Filter::Util::Call: 0
  Getopt::Long: 2.37
  PadWalker: 1.9
  Text::Table: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kan/p5-opts.git
version: 0.042
